<?php
require_once('DBconnect.php');

if(isset($_POST['new_user_name']) && isset($_POST['new_user_password']) && isset($_POST['email']) && isset($_POST['phone_number'])){
	$user_name = $_POST['new_user_name'];
	$user_password = $_POST['new_user_password'];
	$email = $_POST['email'];
	$phone_number = $_POST['phone_number'];

	// user_id will be auto-generated by the database
	$sql = "INSERT INTO user (name, password, email, phone_number) VALUES ('$user_name', '$user_password', '$email', '$phone_number')";

	$result = mysqli_query($conn, $sql);
	echo "ran successfully";
	if(mysqli_affected_rows($conn)){
		header("Location: index.php");
	}
	else{
		header("Location: register_user.php");
	}
}
?>